[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.commerce.carts"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "commerce", "carts"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.commerce.carts"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
